# Generated by Django 2.1.2 on 2018-10-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_veiculo_proprietario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorHora', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valorMes', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
